[package]
name = "test_token"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
candid = "0.10"
icp-token = { path = "icp-token" }
maplit = "1"
