[package]
name = "test_token"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
uncensored-greats-dao = {path = "../../"}
serde = { version = "1", features = ["derive"] }
serde_json = "1"
candid = "0.10"
